id: PAFB18722
initial_creation_type: input
source_metadata:
  title: Amitāyus Series
  language: en
  description: 'Texts related to Amitāyus (tshe dpag med), the Buddha of Boundless
    Life:'
  volume:
    8ddc8937fb4b4976b4e674ee868f6aef:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Lineage Prayers
    57b058914788429680e383358f230c66:
      title: A Prayer to Amitāyus
      parent: Prayers
    e0238b1781d54d349019420e62816794:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    7493772d32cd47138ee3c125f285ec68:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    c68c81dd37eb422aaaaf80e353530d38:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Sādhanas
    4011c2d84a67460c8467bbd6b629573a:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Sādhanas
    c6953921bade44cba454bad8ee454bed:
      title: The Dhāraṇī of Amitāyus
      parent: Sūtra
    9b8a6e05068f4a9f9b272944a22c28ee:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    1a56d5c1ac904cc8bb273005e580c925:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Sūtra
created_at: '2022-03-01T02:43:20.956082'
last_modified_at: '2022-03-01T02:43:20.956088'
